### ISSUE TITLE
大佬,Vue.js devtool好像没法用

### ISSUE THREAD

**Issue by asvue** [Mrminfive/vue-multiple-page#1]
在npm run dev下 Vue.js devtools 识别不了页面,无法进行调试
其次page2这个文件夹能通过访问http://localhost:8009/pages/page2/index.html
index这个页面....请恕我才疏学浅...

**Comment by Mrminfive** [comment]
直接访问page2.html就行，至于devtools的问题，请安装vue Devtools，然后打开开发者面板切换到vue面板

**Comment by asvue** [comment]
@Mrminfive  老哥,上面我问的可能不对,是index这个文件夹里的单页面该怎么访问....和我平时的打开方式不太一样,怎么都打开不了

**Comment by Mrminfive** [comment]
http://localhost:8009/#/home 或者 http://localhost:8009/index.html#/home

**Comment by asvue** [comment]
http://localhost:8009/#/home   报错 Cannot GET /

http://localhost:8009/index.html#/home  报错 Cannot GET /index.html

**Comment by Mrminfive** [comment]
![/#/home](https://user-images.githubusercontent.com/24197735/28917610-cddb262e-7878-11e7-8653-2a66f07eab84.png)

![/index.html#/home](https://user-images.githubusercontent.com/24197735/28917762-5e8194f6-7879-11e7-8694-9be95f54819f.png)
