### ISSUE TITLE
路径分隔符在 mac 和 win 下的差异，导致的错误

### ISSUE THREAD

**Issue by green0511** [Mrminfive/vue-multiple-page#4]
在 `webpack.dev.config.js` 和 `webpack.prod.config.js` 两个文件中，包含如下代码：

```js
let chunkName = template.split('/').slice(-2)[0];
```

但在 **windows** 环境下，路径的分隔符是 `\\`， 故导致了 issue #1 和 #2 

建议将 `'/'` 替换为 `path.sep`

**Comment by green0511** [comment]
issue #3 里提到的 `hot reload` 问题我也遇到了，不过报错信息不一样。

环境如下：
  * 系统：win 7
  * node：v6.11.0
  * npm：v3.10.10

初步判断是 `vue-loader` 似乎不太兼容 `webpack 3` ，我把 `webpack` 和 `extract-text-webpack-plugin` 的版本降到 `2.x`，去掉了 `ModuleConcatenationPlugin`， `hot-reload` 功能目前使用正常

[参考](https://forum.vuejs.org/t/hotapi-install-is-not-a-function/14657)

**Comment by Mrminfive** [comment]
好的，这些问题近期我会修正回来，谢谢你的建议
